dry-run: false

commit-message: "Add backstage configuration file"

pr-body: "See [Slack Announcement](https://hmcts-reform.slack.com/archives/CA4F2MAFR/p1661337390085229)

Ping `@Tim J` on Slack if any questions
"

conflict-strategy: replace

branch: add-backstage-component-info

repo:
  - 'hmcts/aac-manage-case-assignment'
  - 'hmcts/adoption-cos-api'
  - 'hmcts/adoption-shared-infrastructure'
  - 'hmcts/adoption-web'
  - 'hmcts/am-judicial-booking-service'
  - 'hmcts/am-org-role-mapping-service'
  - 'hmcts/am-role-assignment-batch-service'
  - 'hmcts/am-role-assignment-refresh-batch'
  - 'hmcts/am-role-assignment-service'
  - 'hmcts/bar-api'
  - 'hmcts/bar-shared-infrastructure'
  - 'hmcts/bar-web'
  - 'hmcts/blob-router-service'
  - 'hmcts/bulk-scan-ccd-event-handler-sample-app'
  - 'hmcts/bulk-scan-orchestrator'
  - 'hmcts/bulk-scan-payment-processor'
  - 'hmcts/bulk-scan-processor'
  - 'hmcts/bulk-scan-shared-infrastructure'
  - 'hmcts/camunda-bpm'
  - 'hmcts/camunda-shared-infrastructure'
  - 'hmcts/ccd-admin-web'
  - 'hmcts/ccd-api-gateway'
  - 'hmcts/ccd-case-activity-api'
  - 'hmcts/ccd-case-disposer'
  - 'hmcts/ccd-case-document-am-api'
  - 'hmcts/ccd-case-print-service'
  - 'hmcts/ccd-data-store-api'
  - 'hmcts/ccd-definition-store-api'
  - 'hmcts/ccd-elastic-search'
  - 'hmcts/ccd-message-publisher'
  - 'hmcts/ccd-next-hearing-date-updater'
  - 'hmcts/ccd-shared-infrastructure'
  - 'hmcts/ccd-test-stubs-service'
  - 'hmcts/ccd-user-profile-api'
  - 'hmcts/ccfr-fees-register-admin-web'
  - 'hmcts/ccfr-fees-register-app'
  - 'hmcts/ccpay-bubble'
  - 'hmcts/ccpay-bulkscanning-app'
  - 'hmcts/ccpay-cpo-function-node'
  - 'hmcts/ccpay-functions-node'
  - 'hmcts/ccpay-notifications-service'
  - 'hmcts/ccpay-payment-api-gateway'
  - 'hmcts/ccpay-payment-app'
  - 'hmcts/ccpay-payment-status-function-node'
  - 'hmcts/ccpay-paymentoutcome-web'
  - 'hmcts/ccpay-refunds-app'
  - 'hmcts/ccpay-scheduled-jobs'
  - 'hmcts/ccpay-service-request-cpo-update-service'
  - 'hmcts/ccpayfr-shared-infrastructure'
  - 'hmcts/civil-camunda-bpmn-definition'
  - 'hmcts/civil-ccd-definition'
  - 'hmcts/civil-citizen-ui'
  - 'hmcts/civil-general-applications'
  - 'hmcts/civil-general-apps-ccd-definition'
  - 'hmcts/civil-service'
  - 'hmcts/civil-shared-infrastructure'
  - 'hmcts/civil-wa-post-deployment-ft-tests'
  - 'hmcts/civil-wa-task-configuration'
  - 'hmcts/cmc-ccd-e2e-tests'
  - 'hmcts/cmc-citizen-frontend'
  - 'hmcts/cmc-claim-store'
  - 'hmcts/cmc-legal-rep-frontend'
  - 'hmcts/cnp-database-subnet-whitelisting'
  - 'hmcts/cnp-idam-master'
  - 'hmcts/cnp-idam-packer'
  - 'hmcts/cnp-idam-vault'
  - 'hmcts/cnp-keda-shared-infrastucture'
  - 'hmcts/cnp-module-adf'
  - 'hmcts/cnp-module-automation-account'
  - 'hmcts/cnp-module-elk'
  - 'hmcts/cnp-module-key-vault'
  - 'hmcts/cnp-module-postgres'
  - 'hmcts/cnp-module-redis'
  - 'hmcts/cnp-owaspdependencycheck-database'
  - 'hmcts/cnp-plum-batch'
  - 'hmcts/cnp-plum-frontend'
  - 'hmcts/cnp-plum-recipes-service'
  - 'hmcts/cnp-plum-shared-infrastructure'
  - 'hmcts/cpo-case-payment-orders-api'
  - 'hmcts/ctsc-work-allocation'
  - 'hmcts/dg-docassembly-api'
  - 'hmcts/div-case-data-formatter'
  - 'hmcts/div-case-maintenance-service'
  - 'hmcts/div-case-orchestration-service'
  - 'hmcts/div-ccd-definitions'
  - 'hmcts/div-ccd-e2e-tests'
  - 'hmcts/div-decree-absolute-frontend'
  - 'hmcts/div-decree-nisi-frontend'
  - 'hmcts/div-document-generator-client'
  - 'hmcts/div-evidence-management-client-api'
  - 'hmcts/div-fees-and-payments-service'
  - 'hmcts/div-petitioner-frontend'
  - 'hmcts/div-respondent-frontend'
  - 'hmcts/div-shared-infrastructure'
  - 'hmcts/document-management-store-app'
  - 'hmcts/draft-store'
  - 'hmcts/ecm-consumer'
  - 'hmcts/ecm-shared-infrastructure'
  - 'hmcts/em-annotation-api'
  - 'hmcts/em-ccd-orchestrator'
  - 'hmcts/em-hrs-api'
  - 'hmcts/em-hrs-ingestor'
  - 'hmcts/em-icp-api'
  - 'hmcts/em-media-viewer'
  - 'hmcts/em-native-pdf-annotator-app'
  - 'hmcts/em-showcase'
  - 'hmcts/em-stitching-api'
  - 'hmcts/et-ccd-callbacks'
  - 'hmcts/et-ccd-definitions-admin'
  - 'hmcts/et-message-handler'
  - 'hmcts/et-shared-infrastructure'
  - 'hmcts/et-sya-api'
  - 'hmcts/et-sya-frontend'
  - 'hmcts/et-xui-e2e-tests'
  - 'hmcts/ethos-repl-docmosis-service'
  - 'hmcts/fact-admin'
  - 'hmcts/fact-api'
  - 'hmcts/fact-frontend'
  - 'hmcts/fact-shared-infrastructure'
  - 'hmcts/family-api-gateway'
  - 'hmcts/finrem-case-orchestration-service'
  - 'hmcts/finrem-ccd-definitions'
  - 'hmcts/finrem-document-generator-client'
  - 'hmcts/finrem-evidence-management-client-api'
  - 'hmcts/finrem-notification-service'
  - 'hmcts/finrem-payment-service'
  - 'hmcts/finrem-shared-infrastructure'
  - 'hmcts/fis-bulk-scan-api'
  - 'hmcts/fis-cos-api'
  - 'hmcts/fis-ds-update-web'
  - 'hmcts/fis-ds-web'
  - 'hmcts/fis-shared-infrastructure'
  - 'hmcts/fpl-ccd-configuration'
  - 'hmcts/hmc-cft-hearing-service'
  - 'hmcts/hmc-hmi-inbound-adapter'
  - 'hmcts/hmc-hmi-outbound-adapter'
  - 'hmcts/hmc-shared-infrastructure'
  - 'hmcts/hofse-ardoq-api-prototype'
  - 'hmcts/ia-aip-frontend'
  - 'hmcts/ia-bail-case-api'
  - 'hmcts/ia-case-access-api'
  - 'hmcts/ia-case-api'
  - 'hmcts/ia-case-documents-api'
  - 'hmcts/ia-case-notifications-api'
  - 'hmcts/ia-case-payments-api'
  - 'hmcts/ia-ccd-e2e-tests'
  - 'hmcts/ia-hearings-api'
  - 'hmcts/ia-home-office-integration-api'
  - 'hmcts/ia-home-office-mock-api'
  - 'hmcts/ia-shared-infrastructure'
  - 'hmcts/ia-task-configuration'
  - 'hmcts/ia-timed-event-service'
  - 'hmcts/idam-access-config'
  - 'hmcts/idam-api'
  - 'hmcts/idam-config-as-code-poc'
  - 'hmcts/idam-data-provisioning'
  - 'hmcts/idam-forgerock-idm'
  - 'hmcts/idam-java-client'
  - 'hmcts/idam-shared-infrastructure'
  - 'hmcts/idam-testing-support-api'
  - 'hmcts/idam-user-dashboard'
  - 'hmcts/idam-web-admin'
  - 'hmcts/idam-web-public'
  - 'hmcts/lau-case-backend'
  - 'hmcts/lau-frontend'
  - 'hmcts/lau-idam-backend'
  - 'hmcts/lau-shared-infrastructure'
  - 'hmcts/nfdiv-case-api'
  - 'hmcts/nfdiv-ccd-e2e-tests'
  - 'hmcts/nfdiv-frontend'
  - 'hmcts/nfdiv-shared-infrastructure'
  - 'hmcts/pcq-backend'
  - 'hmcts/pcq-consolidation-service'
  - 'hmcts/pcq-frontend'
  - 'hmcts/pcq-loader'
  - 'hmcts/pcq-shared-infrastructure'
  - 'hmcts/prl-ccd-definitions'
  - 'hmcts/prl-citizen-frontend'
  - 'hmcts/prl-cos-api'
  - 'hmcts/prl-dgs-api'
  - 'hmcts/prl-shared-infrastructure'
  - 'hmcts/probate-back-office'
  - 'hmcts/probate-business-service'
  - 'hmcts/probate-caveats-frontend'
  - 'hmcts/probate-frontend'
  - 'hmcts/probate-orchestrator-service'
  - 'hmcts/probate-submit-service'
  - 'hmcts/probatemandb'
  - 'hmcts/rd-caseworker-ref-api'
  - 'hmcts/rd-commondata-api'
  - 'hmcts/rd-commondata-dataload'
  - 'hmcts/rd-judicial-api'
  - 'hmcts/rd-judicial-data-load'
  - 'hmcts/rd-location-ref-api'
  - 'hmcts/rd-location-ref-data-load'
  - 'hmcts/rd-professional-api'
  - 'hmcts/rd-profile-sync'
  - 'hmcts/rd-shared-infrastructure'
  - 'hmcts/rd-user-profile-api'
  - 'hmcts/reform-scan-notification-service'
  - 'hmcts/reform-scan-shared-infra'
  - 'hmcts/rpe-pdf-service'
  - 'hmcts/rpts-api'
  - 'hmcts/rpts-frontend'
  - 'hmcts/rpts-shared-infrastructure'
  - 'hmcts/rpx-shared-infrastructure'
  - 'hmcts/rpx-xui-approve-org'
  - 'hmcts/rpx-xui-manage-organisations'
  - 'hmcts/rpx-xui-webapp'
  - 'hmcts/send-letter-service'
  - 'hmcts/send-letter-service-container-new'
  - 'hmcts/send-letter-service-container-proc'
  - 'hmcts/send-letter-service-container-zip'
  - 'hmcts/service-auth-provider-app'
  - 'hmcts/service-auth-provider-java-client'
  - 'hmcts/sptribs-case-api'
  - 'hmcts/sscs-bulk-scan'
  - 'hmcts/sscs-case-loader'
  - 'hmcts/sscs-case-migration'
  - 'hmcts/sscs-ccd-callback-orchestrator'
  - 'hmcts/sscs-ccd-definitions'
  - 'hmcts/sscs-ccd-e2e-tests'
  - 'hmcts/sscs-cor-frontend'
  - 'hmcts/sscs-evidence-share'
  - 'hmcts/sscs-hearings-api'
  - 'hmcts/sscs-post-deployment-ft-tests'
  - 'hmcts/sscs-shared-infrastructure'
  - 'hmcts/sscs-submit-your-appeal'
  - 'hmcts/sscs-task-configuration'
  - 'hmcts/sscs-track-your-appeal-notifications'
  - 'hmcts/sscs-tribunals-case-api'
  - 'hmcts/ts-translation-service'
  - 'hmcts/wa-case-event-handler'
  - 'hmcts/wa-message-cron-service'
  - 'hmcts/wa-post-deployment-ft-tests'
  - 'hmcts/wa-shared-infrastructure'
  - 'hmcts/wa-standalone-task-bpmn'
  - 'hmcts/wa-task-batch-service'
  - 'hmcts/wa-task-configuration-api'
  - 'hmcts/wa-task-configuration-template'
  - 'hmcts/wa-task-management-api'
  - 'hmcts/wa-task-monitor'
  - 'hmcts/wa-workflow-api'
